# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 421981ceb37e08fbec9b401d6051247ea708865641cd6f0d1362c2d662afafa91042357d1e7e8569c4f96d969e1660a27569892140aaa55c1a2e17b5b164df49

test:
  secret_key_base: e256c683bb0ab724287a6a60b035dd30ad65f2c6d3e5cda50e9d23b4e2429af395e2808596e675b7b6ceeff9a15756c4872a128ae8fd5cdd19b8ad7305e034d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
